### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by afuh** [l1h3r/ex_shla#1]
Hey @l1h3r, 
amazing job!!

I am putting together a couple of wrappers in the [documentation](https://rickandmortyapi.com/documentation/#libraries), it would be awesome if I can add yours. Looks great!

**Comment by l1h3r** [comment]
Thanks for checking this out and for putting together such an awesome API. Feel free to add this wrapper to your docs!

**Comment by afuh** [comment]
Thank you too!
